title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: jekyllrb
github_username:  jekyll

# Jekyll Theme Foundation date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-foundation:
  date_format: "%b %-d, %Y"


header_pages:
  - about.html

# Add logo image path for header logo
# logo: /images/logo.png

# Allows stylesheet override to update Foundation _settings.
# styles:
#   dir: /css/  # Stylesheet directory
#   file: main.css # Stylesheet filename


# Build settings
markdown: kramdown
theme: jekyll-theme-foundation
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.coffee
  - LICENSE.txt
  - yarn.lock
  - package.json
  - README.md
  - jekyll-theme-foundation.gemspec
